# Generated by Django 3.1.3 on 2021-07-09 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='result',
            new_name='is_correct',
        ),
    ]
